"""List the Python files the browser scorer needs, and prove the list is complete.

    python tools/generate_web_manifest.py

The browser runs our actual Python modules under Pyodide rather than a
JavaScript reimplementation, so there is one exercise engine and the
regression dataset validates the code that participants actually run.

To do that it has to fetch the source files, which means knowing which ones.
The list is derived by walking imports from the scoring entry point rather
than maintained by hand, because a hand-maintained list goes stale the moment
someone adds an import and then fails in the browser rather than in the tests.
"""

from __future__ import annotations

import argparse
import ast
import json
import sys
from pathlib import Path
from typing import Optional

REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
ENTRY_POINTS = ("src/live_session.py",)
MANIFEST = REPOSITORY_ROOT / "web" / "python-manifest.json"

# Configuration is read at runtime, so it travels with the code.
CONFIG_FILES = ("config/application.yaml", "config/exercises/STS-001.yaml")


def module_to_path(module: str) -> Optional[Path]:
    """Repository path for one of our own modules, or None if external."""
    if not module.startswith("src"):
        return None
    candidate = REPOSITORY_ROOT / (module.replace(".", "/") + ".py")
    if candidate.exists():
        return candidate
    package = REPOSITORY_ROOT / module.replace(".", "/") / "__init__.py"
    return package if package.exists() else None


def walk_imports(entry: Path) -> set[Path]:
    """Every one of our source files reachable from `entry`."""
    found: set[Path] = set()
    queue = [entry]
    while queue:
        current = queue.pop()
        if current in found:
            continue
        found.add(current)
        tree = ast.parse(current.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            modules: list[str] = []
            if isinstance(node, ast.Import):
                modules = [alias.name for alias in node.names]
            elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
                modules = [node.module]
                # `from src.pose import models` style
                modules += [f"{node.module}.{a.name}" for a in node.names]
            for module in modules:
                path = module_to_path(module)
                if path is not None and path not in found:
                    queue.append(path)
    return found


def package_inits(files: set[Path]) -> set[Path]:
    """Every `__init__.py` needed for the packages those files live in."""
    inits: set[Path] = set()
    for file in files:
        directory = file.parent
        while directory != REPOSITORY_ROOT:
            init = directory / "__init__.py"
            if init.exists():
                inits.add(init)
            directory = directory.parent
    return inits


def build() -> list[str]:
    files: set[Path] = set()
    for entry in ENTRY_POINTS:
        files |= walk_imports(REPOSITORY_ROOT / entry)
    # Package __init__ files have imports of their own — src/__init__.py pulls
    # in src/version.py — so they are walked too, repeatedly until nothing new
    # appears. Adding them without walking them left a file out.
    while True:
        inits = package_inits(files) - files
        if not inits:
            break
        for init in inits:
            files |= walk_imports(init)
        files |= package_inits(files)
    relative = sorted(str(f.relative_to(REPOSITORY_ROOT)) for f in files)
    return relative + list(CONFIG_FILES)


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify, do not write.")
    args = parser.parse_args(argv)

    files = build()
    payload = {
        "note": "Generated by tools/generate_web_manifest.py — do not edit by hand.",
        "entry_points": list(ENTRY_POINTS),
        "files": files,
    }
    text = json.dumps(payload, indent=2) + "\n"

    if args.check:
        if not MANIFEST.exists() or MANIFEST.read_text(encoding="utf-8") != text:
            print("web/python-manifest.json is out of date. Run:", file=sys.stderr)
            print("  python tools/generate_web_manifest.py", file=sys.stderr)
            return 1
        print(f"manifest is current: {len(files)} files")
        return 0

    MANIFEST.write_text(text, encoding="utf-8")
    print(f"wrote {MANIFEST.relative_to(REPOSITORY_ROOT)} — {len(files)} files")
    for name in files:
        print(f"  {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
