/**
 * Runs the project's actual Python exercise engine, in the browser.
 *
 * Pyodide executes the modules from `src/` under WebAssembly — the same code
 * the regression dataset validates, not a JavaScript reimplementation of it.
 * So there is one exercise engine, changes to it reach the browser without
 * being ported, and a participant's movement never leaves their device.
 *
 * It runs in a worker because Pyodide loads several megabytes and then does
 * real work per frame. On the main thread that would stall the video and the
 * pose estimation the scoring depends on.
 *
 * The file list comes from web/python-manifest.json, generated by walking
 * imports from the scoring entry point. A hand-maintained list would go stale
 * the moment someone added an import, and would fail here rather than in the
 * tests.
 */

const PYODIDE_VERSION = "0.26.4";
importScripts(`https://cdn.jsdelivr.net/pyodide/v${PYODIDE_VERSION}/full/pyodide.js`);

let pyodide = null;
let ready = false;

function report(stage, detail = "") {
  self.postMessage({ type: "progress", stage, detail });
}

async function initialise(rootUrl) {
  // Roughly 13 MB the first time: the WebAssembly Python runtime and its
  // standard library. Saying so is better than an unexplained wait — the
  // browser caches it, so later visits skip this entirely.
  report("loading", "Downloading the exercise engine (about 13 MB, first visit only)");
  pyodide = await loadPyodide({
    indexURL: `https://cdn.jsdelivr.net/pyodide/v${PYODIDE_VERSION}/full/`,
  });

  // Configuration is read from YAML at runtime, so the parser has to be here.
  report("loading", "Reading the exercise settings");
  await pyodide.loadPackage("pyyaml");

  report("loading", "Loading the sit-to-stand engine");
  // Absolute URLs throughout. Relative fetches inside a worker resolve
  // against the worker's own location, not the page's, which silently
  // requested the wrong path and returned a 404 HTML page.
  const manifestUrl = new URL("web/python-manifest.json", rootUrl).href;
  const manifestResponse = await fetch(manifestUrl);
  if (!manifestResponse.ok) {
    throw new Error(`could not fetch ${manifestUrl} (${manifestResponse.status})`);
  }
  const manifest = await manifestResponse.json();

  // Fetched together rather than one after another: they are small files and
  // the round trips dominate.
  const sources = await Promise.all(
    manifest.files.map(async (relative) => {
      const url = new URL(relative, rootUrl).href;
      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`could not fetch ${relative} (${response.status})`);
      }
      return [relative, await response.text()];
    }),
  );
  report("loading", `Loaded ${sources.length} files`);

  for (const [relative, text] of sources) {
    const directory = relative.substring(0, relative.lastIndexOf("/"));
    if (directory) pyodide.FS.mkdirTree(`/app/${directory}`);
    pyodide.FS.writeFile(`/app/${relative}`, text);
  }

  report("loading", "Almost ready");
  pyodide.runPython(`
import sys, os
sys.path.insert(0, "/app")
os.chdir("/app")

from src.config import load_config, load_sts_config
from src.exercises.sit_to_stand import SitToStandEngine
from src.live_session import LiveSession
from src.pose.models import PoseFrame
import dataclasses, json

_state = {"session": None}

def start_session(target):
    config = load_config()
    sts = load_sts_config()
    if target:
        sts = dataclasses.replace(sts, target_repetitions=int(target))
    engine = SitToStandEngine(sts)
    engine.initialise()
    _state["session"] = LiveSession(config, engine=engine)
    return json.dumps(_state["session"].status())

def score_frames(payload):
    session = _state["session"]
    if session is None:
        return json.dumps({"error": "no session"})
    events = []
    for raw in json.loads(payload):
        update = session.update(PoseFrame.from_dict(raw))
        events.extend(event.to_dict() for event in update.events)
    status = session.status()
    status["events"] = events
    return json.dumps(status)

def stop_session():
    session = _state["session"]
    if session is None:
        return json.dumps({})
    session.stop()
    result = session.result().to_dict()
    _state["session"] = None
    return json.dumps({"result": result})
`);

  ready = true;
  const version = pyodide.runPython("from src.version import APPLICATION_VERSION; APPLICATION_VERSION");
  self.postMessage({ type: "ready", version });
}

self.onmessage = async (event) => {
  const { type, id } = event.data;
  try {
    if (type === "init") {
      await initialise(event.data.rootUrl);
      return;
    }
    if (!ready) {
      self.postMessage({ type: "error", id, message: "engine not ready" });
      return;
    }
    if (type === "start") {
      const status = pyodide.globals.get("start_session")(event.data.target ?? null);
      self.postMessage({ type: "started", id, status: JSON.parse(status) });
      return;
    }
    if (type === "frames") {
      const status = pyodide.globals.get("score_frames")(
        JSON.stringify(event.data.frames),
      );
      self.postMessage({ type: "status", id, status: JSON.parse(status) });
      return;
    }
    if (type === "stop") {
      const payload = pyodide.globals.get("stop_session")();
      self.postMessage({ type: "stopped", id, ...JSON.parse(payload) });
      return;
    }
  } catch (error) {
    // Say what failed. A silent worker leaves the page waiting forever.
    self.postMessage({ type: "error", id, message: String(error) });
  }
};
